import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FinSight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-zinc-200">
        <header className="w-full bg-zinc-950/50 backdrop-blur-xl border-b border-zinc-800/50 text-white sticky top-0 z-50">
          <div className="max-w-7xl mx-auto flex items-center justify-between py-3 pl-4 pr-6">
            <h1 className="text-xl font-bold tracking-tighter bg-clip-text text-transparent bg-gradient-to-b from-white to-zinc-400 drop-shadow-[0_0_8px_rgba(255,255,255,0.15)]">
              FinSight
            </h1>
          </div>
        </header>
        <main className="flex-1 w-full">
          {children}
        </main>
        <footer className="w-full bg-black py-8 text-center text-[10px] uppercase tracking-[0.2em] text-zinc-600 border-t border-zinc-900 mt-auto">
          <p>&copy; {new Date().getFullYear()} FinSight • Secure AI Financial Analytics</p>
        </footer>
      </body>
    </html>
  );
}
